services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: realmate
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U docker -d realmate"]
      interval: 5s
      timeout: 5s
      retries: 5
  
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://backend:8000
    depends_on:
      - backend
  
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy

  celery:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: celery -A realmate_challenge worker -l info -B --scheduler django_celery_beat.schedulers:DatabaseScheduler
    entrypoint: []
    environment:
      - DATABASE_URL=postgres://docker:docker@db:5432/realmate
      - REDIS_URL=redis://redis:6379/0
      - DJANGO_SETTINGS_MODULE=realmate_challenge.settings
    depends_on:
      - backend

volumes:
  db_data: