# Generated by Django 5.2.3 on 2025-06-16 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_message_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='processed',
            field=models.BooleanField(default=False),
        ),
    ]
