# Generated by Django 5.2.3 on 2025-06-17 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_message_processed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='processed',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
